import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import header from '../../styles/Header.module.css'
import cards from '../../styles/Cards.module.css'
import details from '../../styles/Details.module.css'

import { blenderMovies } from '../../lib/blenderdb'

export default function movieItem({info}) {
      
  return (
    <div className={styles.container}>
      <Head>
        <title>Blender Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <header>
        <nav className={header.menu}>
          <a  href="/" className={header.logo}>Blender Movies</a>
        </nav>
      </header>

      <main className={styles.main}>
        <div className={details.backgroundContainer}>
          <div className={details.contentContainer}>
            <div className={details.videoContainer}>
              <iframe  src={blenderMovies[info].movieLink} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen className={details.videoWrapper}s></iframe>
            </div>
            <div className={details.textContainer}>
              <div className={details.tittleContainer}>
                <h1 className={details.tittle}>{blenderMovies[info].tittle}</h1>
              </div>
              <div> <p className={details.overview}>{blenderMovies[info].overview}</p></div>
            </div>
          </div>
        </div>
        
      </main>

    </div>
  )
}

export async function getServerSideProps(context){
  // const res = await fetch(`http://localhost:3000/api/moviesApi/${context.params.id}`);
  // const json = await res.json();

  const res = context.params.id
  return {
    props: {
      info: res
    }
  }
}